do $$
begin
  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'service_area_zips'
  ) then
    create table public.service_area_zips (
      id bigint generated by default as identity primary key,
      zip text not null,
      active boolean not null default true,
      county text,
      town text,
      price_14_yard_override integer,
      latitude double precision,
      longitude double precision,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint service_area_zips_zip_key unique (zip)
    );
  end if;
end
$$;

create index if not exists service_area_zips_active_idx
  on public.service_area_zips (active);

create index if not exists service_area_zips_zip_idx
  on public.service_area_zips (zip);

do $$
begin
  if exists (
    select 1
    from pg_proc
    where proname = 'set_updated_at'
      and pg_function_is_visible(oid)
  ) then
    drop trigger if exists service_area_zips_set_updated_at on public.service_area_zips;
    create trigger service_area_zips_set_updated_at
    before update on public.service_area_zips
    for each row execute function public.set_updated_at();
  end if;
end
$$;

with seeded(zip, county, town) as (
  values
    ('13031', 'Onondaga', 'Camillus'),
    ('13057', 'Onondaga', 'East Syracuse'),
    ('13066', 'Onondaga', 'Fayetteville'),
    ('13104', 'Onondaga', 'Manlius'),
    ('13108', 'Onondaga', 'Marcellus'),
    ('13152', 'Onondaga', 'Skaneateles'),
    ('13202', 'Onondaga', 'Syracuse'),
    ('13203', 'Onondaga', 'Syracuse'),
    ('13204', 'Onondaga', 'Syracuse'),
    ('13205', 'Onondaga', 'Syracuse'),
    ('13206', 'Onondaga', 'Syracuse'),
    ('13207', 'Onondaga', 'Syracuse'),
    ('13208', 'Onondaga', 'Syracuse'),
    ('13209', 'Onondaga', 'Syracuse'),
    ('13210', 'Onondaga', 'Syracuse'),
    ('13211', 'Onondaga', 'Syracuse'),
    ('13212', 'Onondaga', 'North Syracuse'),
    ('13214', 'Onondaga', 'Syracuse'),
    ('13215', 'Onondaga', 'Syracuse'),
    ('13219', 'Onondaga', 'Syracuse'),
    ('13224', 'Onondaga', 'Syracuse'),
    ('13035', 'Madison', 'Cazenovia'),
    ('13037', 'Madison', 'Chittenango'),
    ('13082', 'Madison', 'Kirkville'),
    ('13122', 'Madison', 'New Woodstock'),
    ('13154', 'Madison', 'Sullivan'),
    ('13346', 'Madison', 'Hamilton'),
    ('13348', 'Madison', 'Lebanon')
)
insert into public.service_area_zips (zip, active, county, town)
select seeded.zip, true, seeded.county, seeded.town
from seeded
on conflict (zip) do update
  set active = true,
      county = excluded.county,
      town = excluded.town,
      updated_at = now();

do $$
begin
  if exists (
    select 1
    from pg_proc
    where proname = 'sync_service_area_zip_coordinates'
      and pg_function_is_visible(oid)
  ) then
    perform public.sync_service_area_zip_coordinates();
  end if;
end
$$;
