import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  formatDetection: {
    telephone: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  <div className="min-h-screen bg-[#F8FAFC]">
    {/* Global Header */}
    <header className="sticky top-0 z-50 bg-[#F8FAFC]/90 backdrop-blur border-b border-slate-200">
      <div className="mx-auto max-w-6xl px-6 py-3 flex items-center justify-between">
        <div className="font-semibold text-[#0F172A]">Tan Can Man</div>
        <a
          className="rounded-2xl border border-slate-300 px-4 py-2 text-sm text-[#0F172A] hover:bg-white"
          href="tel:+1-315-555-0123"
        >
          Call/Text
        </a>
      </div>
    </header>

    {children}

    {/* Global Footer */}
    <footer className="bg-gradient-to-b from-slate-900 to-slate-950 text-slate-200">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="flex flex-col gap-8 md:flex-row md:items-center md:justify-between">

          <div>
            <div className="text-lg font-semibold tracking-tight text-white">
              Tan Can Man
            </div>
            <div className="mt-1 text-slate-300">
              Big Jobs Need Big Cans
            </div>
            <div className="mt-2 text-sm text-slate-400">
              A division of EJs Contractors
            </div>
          </div>

          <div className="text-sm text-slate-400">
            © {new Date().getFullYear()} Tan Can Man. All rights reserved.
          </div>

        </div>
      </div>
    </footer>
  </div>
</body>
    </html>
  );
}
